server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/food_order_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 'Asish@999'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jms:
    template:
      default-destination: order.created
    activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin

camunda:
  bpm:
    database:
      schema-update: true
    job-execution:
      enabled: true
      active: true
    webapp:
      index-redirect: true

jwt:
  secret: SwiggyExpressSecretKey2024_VeryLongSecureKey_AtLeast256Bits!!
  expiration: 86400000

logging:
  level:
    org.camunda.bpm.engine: INFO
    org.springframework.jms: INFO
    org.springframework.security: INFO
